### ISSUE TITLE
Adjust likelihood to give equal weighting to frequency and severity model fit

### ISSUE THREAD

**Issue by ChrisWaller26** [ChrisWaller26/brms_freq_sev#2]

**Comment by ChrisWaller26** [comment]
Currently, there is still a bias in the model towards fitting mu and sigma such that it fits best against severity but not against the deductible adjustment for frequency.

To clarify, in a typical single-response model, the magnitude of the log-likelihood is irrelevant, as the parameter fitting process is independent of scale-factor adjustments to the likelihood. However, this is not true of multi-response models like this one, as frequency is affected by the severity parameters at the deductible, the frequency and severity components contain different numbers of data points and each point contributes differently to the target.

For example, say we have a model with parameters mu = 8, sigma = 1, lambda = 2.5 and we have the following observations:

Loss : 10000, 100 000, 23000
Claim count: 1, 0, 2, 4

The Stan model runs through point-by-point to calculate the log-likelihood and adds this value to the target:

** Contribution to target**

Loss 1: log(lognormal_pdf(10000, 8, 1)) = -10.86174
Loss 2: log(lognormal_pdf(100000, 8, 1)) = -18.60219
Loss 3: log(lognormal_pdf(23000, 8, 1)) = -13.04962
Loss Total: -10.86174 -18.60219 -13.04962 = -42.51355

Claim Count 1: log(poisson_pmf(1, 8, 1)) = -1.583709
Claim Count 2: log(poisson_pmf(0, 8, 1)) = -2.500000
Claim Count 3: log(poisson_pmf(2, 8, 1)) = -1.360566
Claim Count 4: log(poisson_pmf(4, 8, 1)) = -1.542887
Claim Count Total: -1.583709 -2.500000 -1.360566 -1.542887 =  -6.987162

Total Target = -6.987162 -42.51355= -49.50071

Therefore, the severity contributes ~86% to the target but the frequency only contributes ~ 14%.

If frequency and severity weren't linked by the deductible adjustment to the frequency, this wouldn't matter, but in this case it does. It would be great if we could decide the extent we weight the likelihoods, e.g. to give a 50-50 weight.

**Comment by Atan1988** [comment]
Chris, 

     I am still not sure the inherent bias is true or we have model specification issue from the brms translation. Given that the conditional likelihood setup is able to recover the ground up frequencies without bias, I am more inclined to think that stan is able to handle the uneven contribution to the likelihood.  I feel 86%/14% in general isn't actually quite worrisome, I remembered doing the same calculation when I encountered the bias with the main code setup.  Condition on getting close to the optimal mu and sigma parameters space, I think the lambda parameter would instead play an outsized role in the likelihood and should push the sampler to sample the un-biased lambda space.  However, I think it wouldn't be a bad idea to explore the weighting, and see how it might help.  It might be difficult to come up with good heuristic to apply when we don't know the actual distribution parameters. I will test the latest main branch commit after work today. 

PS; Should we post the brms generated code, and the stan code with conditional likelihood setup to the stan forum and see whether someone on the stan development team can help to identify where they are different?

Thanks,
Allen

**Comment by ChrisWaller26** [comment]
I think we've made enough developments that it is worth sharing on the Stan forum again for any feedback they my be able to give us.

One issue I've encountered is that when I add additional parameters to the frequency model, the method of adjusting nlp_claimcount_f1 no longer works because there are now multiple parameters and lambda is a function of them. We therefore need to use mu_claimcount directly. However, given brms currently only lets you paste code either at the beginning or end of the likelihood code, we cannot adjust mu_claimcount for the deductible as at it will not be defined at the top of the code block and at the bottom of the code block it will have already been used in the target += argument.

I have created an alternative method, where I use the str_replace function in the stringr package to modify the code, but this requires us to build the Stan data and code, then running it directly it Stan - thus we will lose a lot of the benefits of brms when it comes to looking at outputs. Can you think of a way around this?

Some questions I would like answering from the Stan team are:

1. Is there a way to add a block of code in-between blocks, rather than just at the  beginning or end?
2. Is there a way to edit the `target +=` arguments directly, if we want to adjust the likelihoods. My current hacky solution is to add a new `target +=` as follows:

If we want `target += poisson_log_lpmf(...) * adjustment_coefficient`, given that we can't remove or edit the `target += poisson_log_lpmf(...)` component, we could create a stanvars argument `target += poisson_log_lpmf(...) * (adjustment_coefficient- 1)`. I'm not sure if there is a better way?

**Comment by Atan1988** [comment]
I think it might not be a big problem. I found how to feed a stan model back into a brms object from the brms package documentation:
#' # fit a model manually via rstan
#' scode <- make_stancode(count ~ Trt, data = epilepsy)
#' sdata <- make_standata(count ~ Trt, data = epilepsy)
#' stanfit <- rstan::stan(model_code = scode, data = sdata)
#' # feed the Stan model back into brms
#' fit8 <- brm(count ~ Trt, data = epilepsy, empty = TRUE)
#' fit8$fit <- stanfit
#' fit8 <- rename_pars(fit8)
#' summary(fit8)
#' }

I think str_replace might not be a bad idea. if we can get it working fairly reliably,  It might be worthwhile to create a function to wrap around all the operations.

**Comment by ChrisWaller26** [comment]
The latest version of the model now gives sensible frequency and severity outputs, without the need to adjust the weighting of the likelihood. Therefore, this may not be much of an issue now.

We can reopen in future if it proves to be a problem down the line, but it is still important to bear in mind.
