### ISSUE TITLE
Modify likelihood weighting

### ISSUE THREAD

**Issue by ChrisWaller26** [ChrisWaller26/brms_freq_sev#33]
Allow the user to modify the weighting of the likelihoods between frequency and severity.

Currently, the un-weighted default is used, which could cause bias towards optimising severity over frequency. There may also be other reasons a user may want to adjust the likelihood weighting, e.g. give less weight to smaller losses or less recent policy years.

**Comment by ChrisWaller26** [comment]
I have discovered that the `weights` argument in BRMS already does this, so there is no need to add this functionality in ourselves

**Comment by Atan1988** [comment]
yeah, it is a bit tricky to use the weights(wei) argument with non-linear specifications. Theoretically, it just treat it as additional observation, but I have a bit hard time wrap my head around how it works in real problems that I have tried to use it.
