### ISSUE TITLE
using macroStan for the template

### ISSUE THREAD

**Issue by spinkney** [ChrisWaller26/brms_freq_sev#36]
I saw your post on discourse and am checking out your repo. I see the template stan code and thought this looked similar to the [macroStan project](https://github.com/Christopher-Peterson/macroStan). It may be useful to you in this project.

**Comment by Atan1988** [comment]
Thank you for the suggestion. I will check out the macroStan project over the weekend.

**Comment by ChrisWaller26** [comment]
This is no longer required, as I have now used the `weights` argument in BRMS to overcome this
