### ISSUE TITLE
brms_freq_sev doesn't work if the shape paramter doesn't have covariates

### ISSUE THREAD

**Issue by Atan1988** [ChrisWaller26/brms_freq_sev#38]
The function seems to translate shape parameter by default to shape_loss[n]/sigma_loss[n] by default. However, if shape parameter is specified to be fitted with a single interception term, then the default brms translation would translate it into a scalar. This would then cause the stan code to error out, due to vector shape[n] is being used in other places in the generated stan code.

**Comment by ChrisWaller26** [comment]
I didn't spot that! It should be straightforward to include an IF condition
to overcome that.
