### ISSUE TITLE
Allow for trends

### ISSUE THREAD

**Issue by ChrisWaller26** [ChrisWaller26/brms_freq_sev#4]

**Comment by ChrisWaller26** [comment]
BRMS already allows for easy modelling of trends without the need to add additional functionality.

For example, if the user wants to allow for inflation in the severity model, they could define a new column in their data, `yr`, which is the number of years after the first year in the data:

`yr = policy_year - min(policy_year)`

The user can then choose to use this as a linear factor, fit a spline or model it in a non-linear way with a structure of their choice:

Linear: `loss ~ 1 + region + yr`
Spline: `loss ~ 1 + region + s(yr)`
Non-Linear: `loss ~ A + B * log(yr), A ~ 1 + region, B ~ 1`

It may be worth including this, as well as other useful worked examples for insurance, in the documentation.

**Comment by Atan1988** [comment]
I agree with you Chris.
