### ISSUE TITLE
Include right censoring by limits into the scope

### ISSUE THREAD

**Issue by Atan1988** [ChrisWaller26/brms_freq_sev#7]
We should probably also include right censoring by limits into the scope.

**Comment by ChrisWaller26** [comment]
This should be straightforward, as we just need to add a column to the severity data which indicates if the limit has been exceeded (`lim_exceed = 1` or `0`). We then add another argument to the severity model, namely:

`loss | subset(sev) + trunc(lb = ded)`

becomes:

`loss | subset(sev) + trunc(lb = ded) + cens(lim_exceed)`

I can make this adjustment and then push the changes. 

Any Stan functions we create ourselves which incorporate severity must also allow for this, but this is not an issue with the current version of the model.
